### ISSUE TITLE
Recommendations is missing

### ISSUE THREAD

**Issue by 4getit** [ryanbradynd05/go-tmdb#11]
Hello,

Not sure if this project is still alive but recommendations are missing. From what I undrstand, they pretty much replaced the 'similar' function.

https://developers.themoviedb.org/3/tv/get-tv-recommendations

**Comment by Funzinator** [comment]
I wouldn't call it inactive. If @ryanbradynd05 didn't start working on that yet, I will try to fit this in next week.
