### ISSUE TITLE
Missing overview in finding

### ISSUE THREAD

**Issue by YouROK** [ryanbradynd05/go-tmdb#19]
Please add "Overview string" in structs MovieShort and TvShort
Like that:

type MovieShort struct {
	Adult         bool
	BackdropPath  string `json:"backdrop_path"`
	ID            int
	OriginalTitle string `json:"original_title"`
	Popularity    float32
	PosterPath    string `json:"poster_path"`
	ReleaseDate   string `json:"release_date"`
	Title         string
	**Overview      string**
	Video         bool
	VoteAverage   float32 `json:"vote_average"`
	VoteCount     uint32  `json:"vote_count"`
}

type TvShort struct {
	Adult         bool
	BackdropPath  string `json:"backdrop_path"`
	ID            int
	OriginalName  string   `json:"original_name"`
	OriginCountry []string `json:"origin_country"`
	Popularity    float32
	PosterPath    string `json:"poster_path"`
	FirstAirDate  string `json:"first_air_date"`
	Name          string
	**Overview      string**
	Video         bool
	VoteAverage   float32 `json:"vote_average"`
	VoteCount     uint32  `json:"vote_count"`
}

**Comment by YouROK** [comment]
And missing genres

**Comment by cyruzin** [comment]
I did a pull request to fix these issues.

**Comment by cyruzin** [comment]
@ryanbradynd05 you may close this one.
