### ISSUE TITLE
Did something break?

### ISSUE THREAD

**Issue by 4getit** [ryanbradynd05/go-tmdb#22]
Hello,

I use go-tmdb since forever but did a later version break things?

I always used to do something like:

```
package main

import "github.com/ryanbradynd05/go-tmdb"

var tmdbApi *tmdb.TMDb

func main() {
	tmdbApi = tmdb.Init("aaaabbbbcccc")
}
```
But this is now throwing error: "cannot use "aaaabbbbcccc" (type string) as type tmdb.Config in argument to tmdb.Init"

And the README.md example doesn't make it very clear because whatever I try, I cannot seem to get things initialized with my key.
Is this a bug perhaps? If not, perhaps an example that is more clear would help.
Thanks!

**Comment by cyruzin** [comment]
Look what I found:

{
	"resource": "/home/cyro/go/src/github.com/cyruzin/go-tmdb/main_test.go",
	"owner": "go-error",
	"severity": 8,
	"message": "cannot use testKey (type string) as type Config in argument to Init",
	"startLineNumber": 41,
	"startColumn": 15,
	"endLineNumber": 41,
	"endColumn": 24
}

**Comment by cyruzin** [comment]
4getit, do this instead:

```
package main

import (
	"fmt"
	"log"

	"github.com/ryanbradynd05/go-tmdb"
)

var tmdbAPI *tmdb.TMDb

func main() {

	config := tmdb.Config{
		APIKey:   "9aca69849a23528a419aea463387945f",
		Proxies:  nil,
		UseProxy: false,
	}

	tmdbAPI = tmdb.Init(config)

	movie, err := tmdbAPI.GetMovieInfo(480530, nil)

	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(movie)

}
```

**Comment by 4getit** [comment]
Great! That works.
Thank you!
