### ISSUE TITLE
Ratelimit on 1fe48e1420500b624f33b38ab6f6d8b4b0ac2053 not working

### ISSUE THREAD

**Issue by Matarc** [ryanbradynd05/go-tmdb#7]
Unfortunately because of a broken implementation on tmdb servers the ratelimiting fix on 1fe48e1420500b624f33b38ab6f6d8b4b0ac2053 is not working.

Here's a test that should be able to show you that it's not working (might have to rerun it or increase the timeout timer)

Don't forget to add your key in the Init function
```go
package tmdb

import (
        "fmt"
        "testing"
        "time"
)

func TestRateLimit(t *testing.T) {
        tmdb := Init("YOUR_KEY") // add your key here
        timer := time.NewTimer(time.Second * 10)
        for {
                select {
                case <-timer.C:
                        fmt.Println("Couldn't break the ratelimit in 10 seconds")
                        return
                default:
                }
                _, err := tmdb.GetFind("tt0137523", "imdb_id", nil)
                if err != nil {
                        t.Fatal(err)
                }
        }
}

**Comment by Matarc** [comment]
By the way in 1fe48e1420500b624f33b38ab6f6d8b4b0ac2053 there's a mistake here https://github.com/ryanbradynd05/go-tmdb/blob/master/main.go#L50

But even fixing that doesn't solve the ratelimit issue

```go
	now := time.Now()
	if rateLimitReset.After(now) { // We have a reset time in the future, so we're out of requests
		// Wait for rate limiter to be reset
		<-time.After(now.Sub(rateLimitReset)) // This is a problem
	}

// It should be instead the following 

	now := time.Now()
	if rateLimitReset.After(now) { // We have a reset time in the future, so we're out of requests
		// Wait for rate limiter to be reset
		<-time.After(rateLimitReset.Sub(now)) 
	}

**Comment by Funzinator** [comment]
I would suggest to close this issue. I wasn't able to reproduce the issue using the test above with the latest code base.
I fired 60 seconds against TMDb and it didn't break. You have to make sure though, that the system where you run this, is synced using NTP. Otherwise the timing is just off.

**Comment by Matarc** [comment]
You're right, the latest code base seems to have solve the issue, thank you for your time :)
